# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14wGctWAipoYAxHo3aTFUf-W-K2_nfDhS
"""

import streamlit as st
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import joblib

# Load the model
model = joblib.load('spam_classifier_model.pkl')

# Streamlit UI
st.title("Mail Classifier")
st.write("This app predicts whether an email is spam or ham (not spam).")

# Input text box
mail_text = st.text_area("Enter an email message:")

if st.button("Predict"):
    if mail_text:
        # Create a list with a single text message
        text_list = [mail_text]

        # Make a prediction using the model
        prediction = model.predict(text_list)

        if prediction == 0:
            st.success("Prediction: Ham (Not Spam)")
        else:
            st.error("Prediction: Spam")
    else:
        st.warning("Please enter an email message to predict.")
